id: I80775E04
default_language: de
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:27.140339
last_modified: 2023-01-04 11:29:27.140355
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  0481:
    title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
    base_file: 0481.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
